name: simplified deploy

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@4
        name: Checkout repo

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - run: npm install
        name: Install Dependencies

      - run: npm run build
        name: Build
        env:
          DATABASE_URL: ${{ vars.DATABASE_URL }}
          DATABASE_AUTH_TOKEN: ${{ vars.DATABASE_AUTH_TOKEN }}

      - uses: azure/webapps-deploy@v3
        name: Deploy
        with:
          app-name: itm-starwars-f-24
          package: ./dist
          publish-profile: ${{ secrets.BE_PUBLISH_PROFILE }}
